#Spring config
spring:
  profiles:
    active: development
  #Token setup
  token:
    issuer: "HiPhim"
    secret: "my mama don't like you and she likes everyone"
    expirationTime: 86400000
  #App42 API
  app42:
    apiKey: "3d3454bbb13b38b2f230bc20f327789fa111ca854f1ade42d5644fbb0e0b7fa6"
    secretKey: "d412fe7e16faecb053606698efe2d667a7c1265285731848f697b316c603abe6"
  banner:
    image:
      location: banner.txt
  #Mail config
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: hiphimd16attt@gmail.com
    password: hiphimd16
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

server:
  servlet:
    #Set cookie age
    session:
      cookie:
        max-age: 86400
        name: "JWT-TOKEN"

#Development Environment config
---
server:
  port: 1010

spring:
  profiles: development
  #MongoDB configuration
  data:
    mongodb:
      uri: mongodb://hiphim:hiphimd16@ds021326.mlab.com:21326/hiphim
      database: hiphim
  origin:
    url: "http://localhost:4200"


#Production Environment config
---
server:
  port: 2020

spring:
  profiles: production
  #MongoDB configuration
  data:
    mongodb:
      uri:
      database:
  origin:
    url: